const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n||0), number=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(n||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='solar-battery-tracker-v1';let seed,data,view='Overview',editIndex=null;
const clone=x=>JSON.parse(JSON.stringify(x)), num=x=>x===''||x==null?null:Number(x), monthName=s=>new Date(s+'T12:00:00').toLocaleDateString('en-GB',{month:'short',year:'numeric'});
function tariff(rows,date){return [...rows].sort((a,b)=>a.date.localeCompare(b.date)).filter(x=>x.date<=date).at(-1)}
function calc(m){
 const r=tariff(data.rates,m.date),c=tariff(data.comparison,m.date);
 if(!r||!c) return {...m,error:'No tariff effective by this month'};
 const vals=['days','generated','exported','importDay','importNight'];
 if(vals.some(k=>m[k]===null||m[k]===undefined||m[k]===''))return {...m,error:'Complete the month’s electricity inputs'};
 if(m.generated<0||m.exported<0||m.exported>m.generated||m.importDay<0||m.importNight<0||m.days<=0||c.nightShare<0||c.nightShare>1)return {...m,error:'Check usage and tariff inputs'};
 const consumed=m.generated-m.exported+m.importDay+m.importNight;
 const actual=m.importDay*r.day+m.importNight*r.night+m.days*r.standing;
 const rate=m.exportOverride==null?r.export:m.exportOverride;
 const exportIncome=m.exported*rate,axle=m.axle||0;
 const comparison=consumed*((1-c.nightShare)*c.day+c.nightShare*c.night)+m.days*c.standing;
 const avoided=comparison-actual,benefit=avoided+exportIncome+axle;
 const gas=m.gasUsed==null?null:m.gasUsed*r.gas+m.days*r.gasStanding;
 return {...m,consumed,actual,exportIncome,axle,comparison,avoided,benefit,gas,eligible:m.date>=data.installDate};
}
function results(){let total=0;return data.months.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(m=>{let x=calc(m);if(!x.error&&x.eligible)total+=x.benefit;return {...x,cumulative:total}})}
function summary(){const rows=results(),eligible=rows.filter(x=>x.eligible&&!x.error),sum=k=>eligible.reduce((a,x)=>a+(x[k]||0),0),cost=Number(data.costSolar)+Number(data.costBattery),benefit=sum('benefit'),average=eligible.length?benefit/eligible.length:null,remaining=Math.max(0,cost-benefit);return {rows,eligible,cost,benefit,average,remaining,avoided:sum('avoided'),exportIncome:sum('exportIncome'),axle:sum('axle'),actual:sum('actual'),comparison:sum('comparison'),gas:sum('gas')}}
const nav=['Overview','Monthly records','Tariffs','Settings'];
function paintNav(){ $('#nav').innerHTML=nav.map(x=>'<button data-nav="'+x+'" class="'+(x===view?'active':'')+'">'+x+'</button>').join('');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;editIndex=null;render()})}
function overview(){
 const s=summary(),p=s.cost>0?s.benefit/s.cost:0,years=s.average>0?s.cost/s.average/12:null,remainYears=s.average>0?s.remaining/s.average/12:null,valid=s.eligible.length;
 const graph=s.rows.filter(x=>x.eligible&&!x.error),max=Math.max(s.cost,...graph.map(x=>x.cumulative),1),w=600,h=195,points=graph.map((x,i)=>[30+(w-45)*(graph.length===1?.5:i/(graph.length-1)),h-18-(h-35)*x.cumulative/max]);
 const line=points.map(p=>p.join(',')).join(' '),costY=h-18-(h-35)*s.cost/max;
 return '<div class="cards"><div class="card"><span>System investment</span><strong>'+money(s.cost)+'</strong></div><div class="card"><span>Saved and earned</span><strong>'+money(s.benefit)+'</strong><small>From '+valid+' complete post-install months</small></div><div class="card"><span>Left to pay back</span><strong>'+money(s.remaining)+'</strong></div><div class="card"><span>Estimated total payback</span><strong>'+(years?years.toFixed(1)+' years':'—')+'</strong><small>'+(remainYears?remainYears.toFixed(1)+' years remaining at current average':'Needs a positive monthly average')+'</small></div></div>'+
 '<div class="layout"><section class="panel"><h2>Payback progress</h2><div class="bar"><i style="width:'+Math.max(0,Math.min(100,p*100))+'%"></i></div><p><b>'+Math.round(p*100)+'%</b> of investment recovered</p><svg class="plot" viewBox="0 0 600 195" role="img" aria-label="Cumulative benefit versus system cost"><line x1="30" x2="590" y1="'+costY+'" y2="'+costY+'" stroke="#db9d29" stroke-width="2" stroke-dasharray="6 5"/><polyline fill="none" stroke="#087f78" stroke-width="4" stroke-linejoin="round" points="'+line+'"/>'+points.map(p=>'<circle cx="'+p[0]+'" cy="'+p[1]+'" r="4" fill="#087f78"/>').join('')+'<text x="32" y="18" fill="#5b7080" font-size="13">Cumulative benefit</text><text x="480" y="'+Math.max(14,costY-7)+'" fill="#986713" font-size="13">System cost</text></svg><p class="hint">The estimate uses the average of complete months since installation. Seasonal changes can make the actual payback date different.</p></section>'+
 '<section class="panel"><h2>Where the benefit came from</h2>'+[['Avoided electricity cost',s.avoided],['Export income',s.exportIncome],['Axle Energy income',s.axle],['Total benefit',s.benefit],['Actual grid electricity cost',s.actual],['Estimated cost without system',s.comparison],['Net electricity position',s.actual-s.exportIncome-s.axle]].map(([a,b])=>'<div class="row"><span>'+a+'</span><b class="'+(b<0?'negative':'')+'">'+money(b)+'</b></div>').join('')+'</section></div>'+
 '<section class="panel"><h2>Recent months</h2>'+table(s.rows.slice(-6).reverse())+'</section>';
}
function table(rows){return '<div class="tablewrap"><table><thead><tr><th>Month</th><th>Solar generated</th><th>Exported</th><th>Grid import</th><th>Actual electricity</th><th>Without system</th><th>Export + Axle</th><th>Monthly benefit</th></tr></thead><tbody>'+rows.map(x=>'<tr data-action="'+esc(x.date)+'"><td>'+monthName(x.date)+(x.eligible?'':' · baseline')+'</td><td class="num">'+number(x.generated)+' kWh</td><td class="num">'+number(x.exported)+' kWh</td><td class="num">'+number((x.importDay||0)+(x.importNight||0))+' kWh</td><td class="num">'+(x.error?'—':money(x.actual))+'</td><td class="num">'+(x.error?'—':money(x.comparison))+'</td><td class="num">'+(x.error?'—':money(x.exportIncome+x.axle))+'</td><td class="num '+(x.benefit<0?'negative':'positive')+'">'+(x.error?esc(x.error):money(x.benefit))+'</td></tr>').join('')+'</tbody></table></div>'}
function field(name,label,value,type='number',step='any'){return '<label>'+label+'<input name="'+name+'" type="'+type+'" '+(type==='number'?'step="'+step+'" min="0"':'')+' value="'+esc(value??'')+'"></label>'}
function monthForm(){
 const m=editIndex===-1?{date:new Date().toISOString().slice(0,7)+'-01',days:30,generated:null,exported:null,importDay:null,importNight:null,gasUsed:null,axle:0,exportOverride:null}:data.months[editIndex];
 return '<section class="panel"><h2>'+(editIndex==null?'Add a month':'Edit '+monthName(m.date))+'</h2><form id="monthForm"><div class="formgrid">'+field('date','Month',m.date.slice(0,7),'month')+field('days','Days billed',m.days)+field('generated','Solar generated (kWh)',m.generated)+field('exported','Exported (kWh)',m.exported)+field('importDay','Imported day (kWh)',m.importDay)+field('importNight','Imported night (kWh)',m.importNight)+field('gasUsed','Gas used (kWh, optional)',m.gasUsed)+field('axle','Axle payment (£)',m.axle)+field('exportOverride','Export rate override (£/kWh, optional)',m.exportOverride)+'</div><p class="hint">Leave the override empty to use Rate History. Zero is a valid override for a month with no export payment.</p><div class="actions"><button class="primary" type="submit">Save month</button><button type="button" id="cancel">Cancel</button>'+(editIndex==null?'':'<button type="button" id="delete">Delete month</button>')+'</div><p id="formError" class="error" role="alert"></p></form></section>'
}
function months(){return '<div class="actions"><button class="primary" id="addMonth">Add month</button></div><p class="hint">Select a row to edit it. March 2026 is kept as a baseline and excluded from payback because installation was on 31 March.</p>'+ (editIndex!==null?monthForm():'')+table(results().slice().reverse())}
function tariffTable(rows,kind){const comp=kind==='comparison';return '<div class="tablewrap"><table><thead><tr><th>Effective from</th><th>Day £/kWh</th><th>Night £/kWh</th><th>Standing £/day</th><th>'+(comp?'Night use share':'Export £/kWh')+'</th>'+(comp?'':'<th>Gas £/kWh</th><th>Gas standing £/day</th>')+'<th></th></tr></thead><tbody>'+rows.map((r,i)=>'<tr>'+[r.date,r.day,r.night,r.standing,comp?r.nightShare:r.export,...(comp?[]:[r.gas,r.gasStanding])].map((v,j)=>'<td>'+ (j===0?esc(v):esc(v??''))+'</td>').join('')+'<td><button data-edit-rate="'+kind+':'+i+'">Edit</button></td></tr>').join('')+'</tbody></table></div>'}
function tariffs(){return '<section class="panel"><h2>Actual tariff history</h2><p class="hint">Rates apply from their effective date until the next change. Values are in pounds and include VAT if entered from a VAT-inclusive bill.</p>'+tariffTable(data.rates,'rates')+'<div class="actions"><button data-add-rate="rates">Add rate change</button></div></section><section class="panel"><h2>Without-system comparison tariff</h2><p class="hint">This is your assumption about the tariff you would have used without solar and battery. It drives the payback estimate.</p>'+tariffTable(data.comparison,'comparison')+'<div class="actions"><button data-add-rate="comparison">Add comparison rate</button></div></section><section id="rateEditor"></section>'}
function settings(){return '<section class="panel"><h2>System settings</h2><form id="settingsForm"><div class="formgrid">'+field('costSolar','Solar installation cost (£)',data.costSolar)+field('costBattery','Battery installation cost (£)',data.costBattery)+field('installDate','Installation date',data.installDate,'date')+'</div><div class="actions"><button class="primary">Save settings</button></div></form></section><section class="panel"><h2>Your data</h2><p>Changes are saved in this browser on this device. Export a backup to move your records to your iPhone or another browser.</p><div class="actions"><button id="export">Export backup</button><label style="display:inline-block"><span class="primary" style="display:inline-block;padding:10px 14px;border-radius:10px;background:#087f78;color:white;cursor:pointer">Import backup</span><input id="import" type="file" accept="application/json,.json" style="position:absolute;width:1px;height:1px;opacity:0"></label><button id="reset">Restore original workbook data</button></div><p id="importError" class="error" role="alert"></p></section><details class="panel"><summary>How calculations work</summary><p>Household electricity used = solar generated − exported + day import + night import. Actual electricity cost = day and night imports at actual rates + standing charge. Estimated cost without the system uses total household use, the comparison tariff and its assumed night share. Monthly benefit = estimated cost without the system − actual electricity cost + export income + Axle payment. Gas is tracked separately and cancels from the electricity comparison.</p><p>Only complete post-install months enter payback. If installation was part-way through a month, enter a separate post-install period for a precise comparison. Tariff changes within a month need a split period for precise billing. This is an estimate based on supplied usage and assumptions; it does not include battery degradation or maintenance.</p></details>'}
function save(){localStorage.setItem(key,JSON.stringify(data))}
function render(){paintNav();$('#app').innerHTML=view==='Overview'?overview():view==='Monthly records'?months():view==='Tariffs'?tariffs():settings();bind()}
function bind(){
 document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>{editIndex=data.months.findIndex(m=>m.date===el.dataset.action);view='Monthly records';render()});
 $('#addMonth')?.addEventListener('click',()=>{editIndex=-1;render()});
 $('#cancel')?.addEventListener('click',()=>{editIndex=null;render()});
 $('#delete')?.addEventListener('click',()=>{if(confirm('Delete this month?')){data.months.splice(editIndex,1);editIndex=null;save();render()}});
 $('#monthForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),m={date:f.get('date')+'-01'};for(const k of ['days','generated','exported','importDay','importNight','gasUsed','axle','exportOverride'])m[k]=num(f.get(k));if(!m.date||!Number.isFinite(m.days)||m.days<1||['generated','exported','importDay','importNight'].some(k=>m[k]===null||m[k]<0)||m.exported>m.generated){$('#formError').textContent='Enter valid electricity figures; exported cannot exceed generated.';return}if(data.months.some((x,i)=>x.date===m.date&&i!==editIndex)){$('#formError').textContent='That month already exists.';return}if(editIndex>=0)data.months[editIndex]=m;else data.months.push(m);editIndex=null;save();render()});
 $('#settingsForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);data.costSolar=num(f.get('costSolar'))||0;data.costBattery=num(f.get('costBattery'))||0;data.installDate=f.get('installDate');save();render()});
 document.querySelectorAll('[data-edit-rate]').forEach(el=>el.onclick=()=>rateForm(...el.dataset.editRate.split(':')));
 document.querySelectorAll('[data-add-rate]').forEach(el=>el.onclick=()=>rateForm(el.dataset.addRate,null));
 $('#export')?.addEventListener('click',()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=u;a.download='solar-battery-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)});
 $('#import')?.addEventListener('change',async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(!Array.isArray(d.months)||!Array.isArray(d.rates)||!Array.isArray(d.comparison)||!d.installDate)throw Error('This is not a Solar & Battery Tracker backup.');data=d;save();render()}catch(err){$('#importError').textContent=err.message}});
 $('#reset')?.addEventListener('click',()=>{if(confirm('Replace all edits on this device with the original workbook figures?')){data=clone(seed);save();render()}});
}
function rateForm(kind,index){index=index==null?null:Number(index);const comp=kind==='comparison',r=index==null?{date:'',day:'',night:'',standing:'',export:'',gas:'',gasStanding:'',nightShare:0}:data[kind][index];$('#rateEditor').innerHTML='<section class="panel"><h2>'+(index==null?'Add':'Edit')+' '+(comp?'comparison':'actual')+' rate</h2><form id="rateForm"><div class="formgrid">'+field('date','Effective from',r.date,'date')+field('day','Day (£/kWh)',r.day)+field('night','Night (£/kWh)',r.night)+field('standing','Standing (£/day)',r.standing)+(comp?field('nightShare','Night share (0–1)',r.nightShare):field('export','Export (£/kWh)',r.export)+field('gas','Gas (£/kWh)',r.gas)+field('gasStanding','Gas standing (£/day)',r.gasStanding))+'</div><div class="actions"><button class="primary">Save rate</button><button type="button" id="cancelRate">Cancel</button>'+(index==null?'':'<button type="button" id="deleteRate">Delete rate</button>')+'</div><p id="rateError" class="error"></p></form></section>';$('#rateEditor').scrollIntoView({behavior:'smooth'});$('#cancelRate').onclick=()=>{$('#rateEditor').innerHTML=''};$('#deleteRate')?.addEventListener('click',()=>{if(data[kind].length>1&&confirm('Delete this rate?')){data[kind].splice(index,1);save();render()}});$('#rateForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),x={date:f.get('date')};for(const k of (comp?['day','night','standing','nightShare']:['day','night','standing','export','gas','gasStanding']))x[k]=num(f.get(k));if(!x.date||Object.values(x).some(v=>v===null||v==='')||x.nightShare>1||data[kind].some((a,i)=>a.date===x.date&&i!==index)){$('#rateError').textContent='Enter all rates and a unique effective date. Night share must be 0–1.';return}if(index==null)data[kind].push(x);else data[kind][index]=x;save();render()}}
fetch('./seed.json').then(r=>r.json()).then(x=>{seed=x;try{data=JSON.parse(localStorage.getItem(key))||clone(seed)}catch{data=clone(seed)}render()}).catch(()=>{$('#app').innerHTML='<p class="notice">Unable to load the starting data. Refresh this page.</p>'});
